### ISSUE TITLE
non-numeric value error

### ISSUE THREAD

**Issue by fritzmg** [fritzmg/contao-inherit-article#5]
```
Warning: A non-numeric value encountered in system\modules\inherit_article\models\ArticleModel_C35.php on line 307

#0 system\modules\inherit_article\models\ArticleModel_C35.php(307): __error(2, 'A non-numeric v...', 'C:\\xampp\\htdocs...', 307, Array)
#1 [internal function]: Contao\ArticleModel::Contao\{closure}(Object(Contao\ArticleModel), Object(Contao\ArticleModel))
#2 system\modules\inherit_article\models\ArticleModel_C35.php(309): usort(Array, Object(Closure))
#3 system\modules\core\library\Contao\Controller.php(242): Contao\ArticleModel::findPublishedByPidAndColumn('0', 'main')
#4 system\modules\core\pages\PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#5 system\modules\core\controllers\FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#6 index.php(20): Contao\FrontendIndex->run()
#7 {main}
```
See also other Contao tickets about this issue. The Models need to be updated.

**Comment by fritzmg** [comment]
fixed in 0390d4380d2937f08a20397428befe073138ce59
